name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go version
      - run: go env
      - run: go mod tidy
      - run: go vet ./...
      - run: CGO_ENABLED=0 go build -v -o linux_safescan -ldflags "-X github.com/Mingcharun/Linux_safescan/internal/config.Version=${{ github.sha }}" ./cmd/linux_safescan
      - run: file linux_safescan
      - run: ./linux_safescan --version
      - uses: actions/upload-artifact@v4
        with:
          name: linux_safescan-${{ github.sha }}
          path: linux_safescan
